image: Visual Studio 2017
environment:
  PROJECT_FILE: ./SimpleTemplate/SimpleTemplate.csproj
  TEST_PROJECT_FILE: ./SimpleTemplate.Tests/SimpleTemplate.Tests.csproj
  COVERALLS_REPO_TOKEN:
    secure: 41T+UsqgAeBVUiAWxGQ240cVaC4U5M/KKZbrBJQlaNfIjtfixClwv4yX5SA3SP1Z
  CODECOV_REPO_TOKEN:
    secure: 1amhErB+ISmrlxsoCUI5QVGGZCfbJdqZ50ygV4Br6iP0QN15tjjv2utuSPxOYACk
install:
  - cmd: dotnet restore %PROJECT_FILE%
  - cmd: dotnet restore %TEST_PROJECT_FILE%
build_script:
  - cmd: dotnet build %PROJECT_FILE%
  - cmd: dotnet build %TEST_PROJECT_FILE%
test_script:
  - cmd: dotnet test %TEST_PROJECT_FILE%
  - bash coverage.sh
  - bash coveralls.sh
  - bash codecov.sh
